### ISSUE TITLE
Recomendaciones de mejora

### ISSUE THREAD

**Issue by gaposx** [sol1303/lim-2018-05-bc-core-am-datadashboard#2]
**GENERAL**
* Tengan cuidado con los elementos que se muestran en la interfaz. Cuando se carga el proyecto se muestran opciones repetidas ("General", "Por Curso", "Por Alumna, "Volver", "Cerrar Sesión").

**HTML**
* No olvides validar tu HTML, revisa [esta URL](https://validator.w3.org/nu/?doc=https%3A%2F%2Ffiorellasaro.github.io%2Flim-2018-05-bc-core-am-datadashboard%2Fsrc%2F) para que observes tus errores y advertencias.
* Te sugerimos usar más etiquetas semánticas como `<header>`, `<footer>`.

**JS**
* Ten en cuenta que tu código debe funcionar en cualquier caso (con cualquier _cohort_). Te recomendamos que recorras la data que recibe la función en lugar de poner propiedades específicas ya que si hubieran más cursos este código dejaría de funcionar.
* No olvides eliminar tus invocaciones para _debuggear_.
* Para proyectos futuros, te sugerimos seguir la [guía de estilos de Laboratoria sobre JS](https://github.com/Laboratoria/js-style-guide).
* Tener cuidado con la declaración de variables que luego no se usen (`data.js`: unit) y también con el uso de variables que nunca fueron declaradas (`main.js`: cell).
* Revisar que no se usen `;` no requeridos.
* ¡Ojo! usar JQuery no era permitido (`main.js`).
* Recuerda que uno de los requerimientos del proyecto era estar implementado completamente en ES6, para ello, también deberías usar el `for..of` y usar _arrow functions_.
* Te recomendamos dividir mejor tu código y crear funciones con su respectiva funcionalidad, por ejemplo en la función `getProgress`.

**GitHub**
* No olvides el uso de los issues y milestones para la organización y asignación de responsabilidades. Te ayudará a llevar un seguimiento de su progreso.

**CSS**
* No olvides reutilizar clases e indentar tu código.
* Ten cuidado con el nombre de las clases, no tienen que ser en nomenclatura camelCase sino separadas con guiones `-`.

Buen trabajo!

**Comment by sol1303** [comment]
Hola, en General cuando dices que se muestran opciones repetidas ¿te refieres a que no se utilizan?

**Comment by sol1303** [comment]
Hola al primer punto de JS dices que recorra la función sin poner propiedades especificas, ¿me podrías decir a cual de las funciones te refieres? 
Y por la parte de UX y UI ¿cual sería tu opinión?

**Comment by gaposx** [comment]
Hola!

> en General cuando dices que se muestran opciones repetidas ¿te refieres a que no se utilizan?

No realmente. Me refiero a que se repiten las opciones en tu sidebar:

![sidebar](https://user-images.githubusercontent.com/539819/42708258-621c1180-86a2-11e8-90ed-f1377e1c7a67.png)

> primer punto de JS dices que recorra la función sin poner propiedades especificas, ¿me podrías decir a cual de las funciones te refieres?

Por ejemplo, esta línea:
```javascript 
onlyProgress[key].intro.percent
```
En el código se asume que el objeto `onlyProgress[key]` va a tener una propiedad (curso) `intro`. Pero si seleccionáramos otro _cohort_ puede ser que no exista ese curso.

> Y por la parte de UX y UI ¿cual sería tu opinión?

Algunos comentarios generales sobre tu interfaz:
- La repetición de elementos del sidebar confundiría a un usuario.
- El usar una imagen de usuario con su nombre y cargo, implica que tendrá un login, pero no veo componentes que soporten esta funcionalidad.
-  Existe un botón (`burger menu`) que no tiene funcionalidad.

Sobre la pantalla principal:
- Es un poco fastidioso para el usuario que un componente (select de sede y cohorts) cambie de tamaño cuando cambian sus valores internos.
- Al momento de cargar el proyecto en una pantalla de resolución diferente a un desktop, no puedo usar los _selects_.
- Sugiero no incluir componentes que no puedan usarse aún (botón _Ver +_).

@gabx04 está realizando la revisión UX y enviará comentarios más específicos por issues en los próximos días.
